[theme]
primaryColor = "#b0894f"
backgroundColor = "#faf8f4"
secondaryBackgroundColor = "#ffffff"
textColor = "#171a21"
font = "sans serif"
baseRadius = "medium"

[theme.sidebar]
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#faf8f4"
textColor = "#171a21"

[server]
enableXsrfProtection = true

[browser]
gatherUsageStats = false
